### ISSUE TITLE
Intel build fails (again) on Ubuntu 16.04

### ISSUE THREAD

**Issue by hanse-windriver** [WindRiver-OpenSourceLabs/wr-core#10] opened 2016-07-05 14:47 UTC
Something is weird with the **Ubuntu 16.04** environment.

Building the Pulsar-8 branch on an Ubuntu 16.04 build machine fails first with the SDL error previous described and after fixing that by commenting out   `#ASSUME_PROVIDED += "libsdl-native"` in `local.conf` it fails again on `consul-migrate` with some go-linker problems.

_| DEBUG: Executing shell function do_compile # 
| github.com/hashicorp/consul-migrate
| /opt/windriver2/workspace/Pulsar8-Intel/wr-core/build-intel-x86/tmp/sy
| sroots/x86_64-linux/usr/lib/x86_64-wrs-linux/go/pkg/tool/linux_amd64/l
| ink: running x86_64-wrs-linux-gcc failed: exit status 1
| /opt/windriver2/workspace/Pulsar8-Intel/wr-core/build-intel-x86/tmp/sysroots/x86_64-linux/usr/libexec/x86_64-wrs-linux/gcc/x86_64-wrs-linux/5.2.0/ld: /tmp/go-link-374498530/000002.o: unrecognized relocation (0x2a) in section .text
| /opt/windriver2/workspace/Pulsar8-Intel/wr-core/build-intel-x86/tmp/sy
| sroots/x86_64-linux/usr/libexec/x86_64-wrs-linux/gcc/x86_64-wrs-linux/
| 5.2.0/ld: final link failed: Bad value
| collect2: error: ld returned 1 exit status
|
| WARNING: /opt/windriver2/workspace/Pulsar8-Intel/wr-core/build-intel-x86/tmp/work/core2-64-wrs-linux/consul-migrate/git-r0/temp/run.do_compile.3212:1 exit 2 from
|   go install github.com/hashicorp/consul-migrate
| ERROR: Function failed: do_compile (log file is located at 
| /opt/windriver2/workspace/Pulsar8-Intel/wr-core/build-intel-x86/tmp/wo
| rk/core2-64-wrs-linux/consul-migrate/git-r0/temp/log.do_compile.3212)
ERROR: Task 5375 (/opt/windriver2/workspace/Pulsar8-Intel/wr-core/layers/meta-overc/meta-cube/recipes-connectivity/consul/consul-migrate_git.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3641 tasks of which 3637 didn't need to be rerun and 1 failed.
ERROR: Command execution failed: Stopped build_

Same error appeared on two different **Ubuntu 16.04** machines.

When I  switched to an **Ubuntu 12.04** server I did not get any of the above problems and my build finished succesfully.

**Comment by masselstine** [comment] 2016-09-16 03:03
This is an interplay between binutils 2.25 and go-cross 1.6.2. Using binutils 2.27 is a potential workaround but would need to be validated to ensure we aren't just trading one issue for another.

**Comment by masselstine** [comment] 2016-09-29 13:36
Just a quick update on this issue. Jason was able to determine the cause and implement a fix which was merged to meta-virtualization. Unfortunately the fix was not complete and caused some unwanted side effects and the fix was reverted. We have now determined the remaining issues and will be merging the complete solution over the coming days. Once these latest changes are merged this issue can be closed.

**Comment by masselstine** [comment] 2016-10-19 13:26
This should be fixed now with the following commits:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=58bc830e732a694ddbdfef8f548387f715bb013c

and
http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=d866c439cb11d1070f169a5385071dc9a6f8b13b

**Closed** 2016-10-19 13:35 UTC
