### ISSUE TITLE
Pulsar-8: Build kernel for MicroZed board is not successful

### ISSUE THREAD

**Issue by iotvietmember** [WindRiver-OpenSourceLabs/wr-core#102] opened 2018-04-09 17:01 UTC
Hello everybody,
When I try to build kernel for MicroZed board (xilinx-zynq), I meet error 
`PNBLACKLIST[linux-windriver] = "Recipe not buildable without local kernel git"`

2. I try to enable unsupported packages with PNWHITELIST follow by 
[this link](https://knowledge.windriver.com/en-us/000_Products/000/010/050/040/000_Wind_River_Linux_Platform_Developer's_Guide%2C_9/060/050/040)

But perhaps I need to have linux kernel source on local.

` which triggered exception FetchError: Fetcher failure: Fetch command failed with exit code 128, output:
fatal: '/home/xxx/wr-core/layers/wr-kernel/recipes-kernel/linux/../../git/kernel-4.1.x.git' does not appear to be a git repository
fatal: Could not read from remote repository.`

Could you please help me create local kernel git and fix this problem?

Many thanks,

**Comment by masselstine** [comment] 2018-04-10 21:12
Can you provide the steps you took to create your build? I want to have the best shot I can at reproducing the issue.

**Comment by iotvietmember** [comment] 2018-04-11 16:04
Hi @masselstine ,

The steps:
 a. Clone wr-core git repo on your host:
     $ git clone -b pulsar-8 --recurse-submodules https://github.com/WindRiver-OpenSourceLabs/wr-core

  b. Check for required host packages and do installation if needed:
     $ cd wr-core
     $ ./scripts/host_package_install.sh --install --yes

c.
. init-xilinx-zynq-env
 bitbake -c menuconfig linux-windriver

Many thanks for your support!

**Comment by masselstine** [comment] 2018-04-11 18:19
If you inspect the contents of 'init-xilinx-zynq-env' you will find that the kernel is specified as linux-yocto:
PREFERRED_PROVIDER_virtual/kernel_xilinx-zynq = "linux-yocto"

and also in the configuration, as you noted, the linux-windriver kernel is blacklisted:
PNBLACKLIST[linux-windriver] = "Recipe not buildable without local kernel git"

If you wish to configure the kernel and you are ever uncertain as to which kernel is in use simply use the 'virtual/kernel' alias:
bitbake -c menuconfig virtual/kernel

This should work for you. I am concerned that you are following a document which has an error in it or similar. Are you following some documentation which is giving you the impression the linux-windriver kernel should be used?

**Comment by iotvietmember** [comment] 2018-04-12 13:53
Thanks @masselstine . 
It means that Wind River Pulsar 8 is not suitable for Xilinx Zynq, namely MicroZed board?

**Comment by masselstine** [comment] 2018-04-12 14:11
I am not certain that conclusion is valid. I was only attempting to solve your immediate build issue which can be explained by the kernel selection, ie. linux-yocto vs. linux-windriver. If you simply allow the linux-yocto kernel to be used as specified your build should be OK.

As far as I know the resulting build will be suitable for the MircoZed board. Not having a suitable target available to me to validate this assertion I will have to defer to @jwessel or @lifupan.

Lacking any indication that there were documents pointing to the use of linux-windriver and if the instructions from [here](https://github.com/WindRiver-OpenSourceLabs/wr-core/blob/pulsar-8/docs/README-xilinx-zynq.TXT) are followed that your build will be successful I believe we can close this issue.

If you have any runtime issues with the resulting build I suggest you create new issue records which will allow us to address them.

**Comment by iotvietmember** [comment] 2018-04-12 14:30
Hi,
I try to do follow your link, but I meet errors as the below code:

```
root@abc-pc:~/BuildPulsar/wr-core/build-xilinx-zynq# bitbake cube-server cube-dom0 cube-essential
Traceback (most recent call last):
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/bin/bitbake", line 33, in <module>
    import bb
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/__init__.py", line 77, in <module>
    from bb import fetch2 as fetch
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/fetch2/__init__.py", line 1769, in <module>
    from . import wget
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/fetch2/wget.py", line 40, in <module>
    from   bs4 import BeautifulSoup
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bs4/builder/__init__.py", line 311, in <module>
    from . import _html5lib
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/event.py:118: RuntimeWarning: Parent module 'bb' not found while handling absolute import
  from bb.msg import BBLogFormatter
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/event.py", line 118, in print_ui_queue
    from bb.msg import BBLogFormatter
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/__init__.py", line 77, in <module>
    from bb import fetch2 as fetch
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/fetch2/__init__.py", line 39, in <module>
    from bb import data
ImportError: cannot import name data
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/event.py", line 118, in print_ui_queue
    from bb.msg import BBLogFormatter
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/__init__.py", line 77, in <module>
    from bb import fetch2 as fetch
  File "/home/abc/BuildPulsar/wr-core/layers/bitbake/lib/bb/fetch2/__init__.py", line 39, in <module>
    from bb import data
ImportError: cannot import name data
```

seems to have bugs in python code. I use Ubuntu Desktop 17.10

**Comment by masselstine** [comment] 2018-04-12 16:10
Ideally you should create a new issue report as we have gone from a kernel issue which I believe is resolved to a bitbake issue. Issue #s don't cost anything it keeping this separation will help others who might follow.

At any rate I can reproduce your failure. It appears that the version of python-html5lib which is installed on 17.10 does not have the '_base' attribute.  I didn't look to see if this is transient or new to all recent versions of the library, I know that on ubu 16.04 this was not the case. I also didn't look to see if bitbake has been updated to account for this change. At any rate it is an issue with the version of bitbake that is used with the pulsar-8 branch when used in conjunction with 17.10.

At any rate you can opt to remove python-html5lib (sudo apt remove python-html5lib) as it is not required to build. Alternatively I suggest you use a Ubu 16.04 builder (Baremetal, VM or container should be fine) to complete your build.

**Comment by masselstine** [comment] 2018-04-12 16:12
Since we have resolved the original issue and the reporter hasn't indicated that there is any documentation errors around use of the linux-windriver vs. linux-yocto kernel we can close this issue. Please create new issue reports for any newly discovered build  or runtime issues.

**Closed by masselstine** 2018-04-12 16:12 UTC
